name: API Docker Image Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t simple_notes/simple_notes:${{ github.sha }} .

      - name: Inject SECRETS
        shell: bash
        run: |
          echo "DEEP_TRANSLATE_API_KEY=${{ secrets.DEEP_TRANSLATE_API_KEY }}" > ${{ github.workspace }}/.env

      - name: Prepare Docker Context
        run: cp .env .

      - name: Bake Env Vars Into Docker Image
        run: docker build -f Dockerfile -t simple_notes/simple_notes:${{ github.sha }} .

      - name: Log In To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: docker push simple_notes/simple_notes:${{ github.sha }}
