name: API Docker Image Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          tags: simple_notes/simple_notes:${{ github.sha }}
          push: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          secrets: |
            DEEP_TRANSLATE_API_KEY=${{ secrets.DEEP_TRANSLATE_API_KEY }}
