 name: Python Test and Coverage Check
 on: [push, pull_request]
 jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install Poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Add dependences
      run: poetry add pytest
    - name: Run Servers in Background
      run: |
        poetry run python -m app.main flask run --host=0.0.0.0 --port=8080 &
        poetry run streamlit run app/frontend.py --server.address=0.0.0.0 --server.port=8501 &
        sleep 10
    - name: Run Integration Tests
      run: poetry run pytest tests/frontend_ui.py